services:
  web: 
    # Dockerfileを使ってイメージをビルド
    build: . 
    ports:
      - "8080:80"
    volumes: # ボリュームのマウント
      - web_data:/usr/share/nginx/html 

volumes:
  # 新しく定義する場合
  web_data:

  # 既存のvolumeを使う場合
  # web_data:
  #   external: true
