services:
  sv1:
    image: alpine:latest
    networks:
      - my-bridge-network
    # エラーを出さないためのコマンド
    command: ["tail", "-f", "/dev/null"] 

  sv2:
    image: alpine:latest
    networks:
      - my-bridge-network
    # エラーを出さないためのコマンド
    command: ["tail", "-f", "/dev/null"] 

networks:
  my-bridge-network:
    driver: bridge